# Generated by Django 5.0.7 on 2024-08-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('id_ahorro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ahorro')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('monto_ahorro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Ahorro')),
                ('fecha_ahorro', models.DateField(verbose_name='Fecha de Ahorro')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Préstamo')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial')),
                ('plazo_meses', models.IntegerField(verbose_name='Plazo en Meses')),
                ('capital_pendiente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capital Pendiente')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('fecha_primera_cuota', models.DateField(blank=True, null=True, verbose_name='Fecha de Primera Cuota')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('estatus_prestamo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estatus del Préstamo')),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id_retiro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Retiro')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('monto_retiro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Retiro')),
                ('fecha_retiro', models.DateField(verbose_name='Fecha de Retiro')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tipo de Pago')),
                ('tipo_pago', models.CharField(max_length=50, verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id_tipo_prestamo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tipo de Préstamo')),
                ('tipo_prestamo', models.CharField(max_length=50, verbose_name='Tipo de Préstamo')),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interés')),
                ('mora', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mora')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('monto_ahorro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de Ahorro')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Trabajo')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('fecha_ingreso_trabajo', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso al Trabajo')),
                ('direccion_trabajo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Trabajo')),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Trabajo')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso a la Cooperativa')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida de la Cooperativa')),
                ('estatus', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estatus')),
                ('referido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referido por')),
                ('ultima_conexion', models.DateField(blank=True, null=True, verbose_name='Última Conexión')),
                ('tipo_usuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Capital')),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Interés')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestamo', verbose_name='Préstamo')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipopago', verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_tipo_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoprestamo', verbose_name='Tipo de Préstamo'),
        ),
    ]
