# Generated by Django 5.0.7 on 2024-08-10 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id_tipo_operacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tipo de Operacion')),
                ('tipo_operacion', models.CharField(max_length=50, verbose_name='Tipo de Operacion')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id_operacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Operacion')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha_operacion', models.DateField(verbose_name='Fecha de operacion')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario')),
                ('id_tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipooperacion', verbose_name='Tipo de Operacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Ahorro',
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_prestamo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_tipo_pago',
        ),
        migrations.DeleteModel(
            name='Retiro',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='TipoPago',
        ),
    ]
