# Generated by Django 5.0.7 on 2024-08-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tipooperacion_transacciones_delete_ahorro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estatus',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Is Active'),
        ),
    ]
