<?php require_once('Connections/sgstec.php'); ?>
<?php
@$cedula=$_POST['sitio2'];
@$sitio=$_POST['sitio'];

?>
<?php
if ($sitio === '2021'){
$query2=sprintf("SELECT * FROM ahorros_2021 WHERE cedula LIKE '$cedula'");
$query3=sprintf("SELECT * FROM retirable_2021 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$resultado3=mysqli_query($sgstec,$query3);
$row2 = mysqli_fetch_assoc($resultado2);
$row3 = mysqli_fetch_assoc($resultado3);
@$aporte_enero=@$row2['aporte_enero'];
@$comentarios_enero=@$row2['comentarios_enero'];
@$aporte_febrero=@$row2['aporte_febrero'];
@$comentarios_febrero=@$row2['comentarios_febrero'];
@$aporte_marzo=@$row2['aporte_marzo'];
@$comentarios_marzo=@$row2['comentarios_marzo'];
@$aporte_abril=@$row2['aporte_abril'];
@$comentarios_abril=@$row2['comentarios_abril'];
@$aporte_mayo=@$row2['aporte_mayo'];
@$comentarios_mayo=@$row2['comentarios_mayo'];
@$aporte_junio=@$row2['aporte_junio'];
@$comentarios_junio=@$row2['comentarios_junio'];
@$aporte_julio=@$row2['aporte_julio'];
@$comentarios_julio=@$row2['comentarios_julio'];
@$aporte_agosto=@$row2['aporte_agosto'];
@$comentarios_agosto=@$row2['comentarios_agosto'];
@$aporte_septiembre=@$row2['aporte_septiembre'];
@$comentarios_septiembre=@$row2['comentarios_septiembre'];
@$aporte_octubre=@$row2['aporte_octubre'];
@$comentarios_octubre=@$row2['comentarios_octubre'];
@$aporte_noviembre=@$row2['aporte_noviembre'];
@$comentarios_noviembre=@$row2['comentarios_noviembre'];
@$aporte_diciembre=@$row2['aporte_diciembre'];
@$comentarios_diciembre=@$row2['comentarios_diciembre'];
@$aporte_enero3=@$row3['aporte_enero'];
@$retiros_enero3=@$row3['retiros_enero'];
@$aporte_febrero3=@$row3['aporte_febrero'];
@$retiros_febrero3=@$row3['retiros_febrero'];
@$aporte_marzo3=@$row3['aporte_marzo'];
@$retiros_marzo3=@$row3['retiros_marzo'];
@$aporte_abril3=@$row3['aporte_abril'];
@$retiros_abril3=@$row3['retiros_abril'];
@$aporte_mayo3=@$row3['aporte_mayo'];
@$retiros_mayo3=@$row3['retiros_mayo'];
@$aporte_junio3=@$row3['aporte_junio'];
@$retiros_junio3=@$row3['retiros_junio'];
@$aporte_julio3=@$row3['aporte_julio'];
@$retiros_julio3=@$row3['retiros_julio'];
@$aporte_agosto3=@$row3['aporte_agosto'];
@$retiros_agosto3=@$row3['retiros_agosto'];
@$aporte_septiembre3=@$row3['aporte_septiembre'];
@$retiros_septiembre3=@$row3['retiros_septiembre'];
@$aporte_octubre3=@$row3['aporte_octubre'];
@$retiros_octubre3=@$row3['retiros_octubre'];
@$aporte_noviembre3=@$row3['aporte_noviembre'];
@$retiros_noviembre3=@$row3['retiros_noviembre'];
@$aporte_diciembre3=@$row3['aporte_diciembre'];
@$retiros_diciembre3=@$row3['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2021</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Comentarios</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".$comentarios_enero."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".$comentarios_febrero."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".$comentarios_marzo."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".$comentarios_abril."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".$comentarios_mayo."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".$comentarios_junio."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".$comentarios_julio."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".$comentarios_agosto."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".$comentarios_septiembre."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".$comentarios_octubre."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".$comentarios_noviembre."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".$comentarios_diciembre."</td></tr></table></center>";
echo"<table class='table'><th style='border: none;'><b>Ahorros Retirables 2021</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>$aporte_enero3</td><td>$retiros_enero3</td></tr><tr><td>Febrero</td><td>$aporte_febrero3</td><td>$retiros_febrero3</td></tr><tr><td>Marzo</td><td>$aporte_marzo3</td><td>$retiros_marzo3</td></tr><tr><td>Abril</td><td>$aporte_abril3</td><td>$retiros_abril3</td></tr><tr><td>Mayo</td><td>$aporte_mayo3</td><td>$retiros_mayo3</td></tr><tr><td>Junio</td><td>$aporte_junio3</td><td>$retiros_junio3</td></tr><tr><td>Julio</td><td>$aporte_julio3</td><td>$retiros_julio3</td></tr><tr><td>Agosto</td><td>$aporte_agosto3</td><td>$retiros_agosto3</td></tr><tr><td>Septiembre</td><td>$aporte_septiembre3</td><td>$retiros_septiembre3</td></tr><tr><td>Octubre</td><td>$aporte_octubre3</td><td>$retiros_octubre3</td></tr><tr><td>Noviembre</td><td>$aporte_noviembre3</td><td>$retiros_noviembre3</td></tr><tr><td>Diciembre</td><td>$aporte_diciembre3</td><td>$retiros_diciembre3</td></tr></table></center>";
$ahorro_2021=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>


<?php
if ($sitio === '2020'){
$query2=sprintf("SELECT * FROM ahorros_2020 WHERE cedula LIKE '$cedula'");
$query3=sprintf("SELECT * FROM retirable_2020 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$resultado3=mysqli_query($sgstec,$query3);
$row2 = mysqli_fetch_assoc($resultado2);
$row3 = mysqli_fetch_assoc($resultado3);
$aporte_enero=$row2['aporte_enero'];
$comentarios_enero=$row2['comentarios_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$comentarios_febrero=$row2['comentarios_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$comentarios_marzo=$row2['comentarios_marzo'];
$aporte_abril=$row2['aporte_abril'];
$comentarios_abril=$row2['comentarios_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$comentarios_mayo=$row2['comentarios_mayo'];
$aporte_junio=$row2['aporte_junio'];
$comentarios_junio=$row2['comentarios_junio'];
$aporte_julio=$row2['aporte_julio'];
$comentarios_julio=$row2['comentarios_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$comentarios_agosto=$row2['comentarios_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$comentarios_septiembre=$row2['comentarios_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$comentarios_octubre=$row2['comentarios_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$comentarios_noviembre=$row2['comentarios_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$comentarios_diciembre=$row2['comentarios_diciembre'];
$aporte_enero3=$row3['aporte_enero'];
$retiros_enero3=$row3['retiros_enero'];
$aporte_febrero3=$row3['aporte_febrero'];
$retiros_febrero3=$row3['retiros_febrero'];
$aporte_marzo3=$row3['aporte_marzo'];
$retiros_marzo3=$row3['retiros_marzo'];
$aporte_abril3=$row3['aporte_abril'];
$retiros_abril3=$row3['retiros_abril'];
$aporte_mayo3=$row3['aporte_mayo'];
$retiros_mayo3=$row3['retiros_mayo'];
$aporte_junio3=$row3['aporte_junio'];
$retiros_junio3=$row3['retiros_junio'];
$aporte_julio3=$row3['aporte_julio'];
$retiros_julio3=$row3['retiros_julio'];
$aporte_agosto3=$row3['aporte_agosto'];
$retiros_agosto3=$row3['retiros_agosto'];
$aporte_septiembre3=$row3['aporte_septiembre'];
$retiros_septiembre3=$row3['retiros_septiembre'];
$aporte_octubre3=$row3['aporte_octubre'];
$retiros_octubre3=$row3['retiros_octubre'];
$aporte_noviembre3=$row3['aporte_noviembre'];
$retiros_noviembre3=$row3['retiros_noviembre'];
$aporte_diciembre3=$row3['aporte_diciembre'];
$retiros_diciembre3=$row3['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2020</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Comentarios</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".$comentarios_enero."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".$comentarios_febrero."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".$comentarios_marzo."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".$comentarios_abril."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".$comentarios_mayo."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".$comentarios_junio."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".$comentarios_julio."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".$comentarios_agosto."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".$comentarios_septiembre."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".$comentarios_octubre."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".$comentarios_noviembre."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".$comentarios_diciembre."</td></tr></table></center>";
echo"<table class='table'><th style='border: none;'><b>Ahorros Retirables 2020</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>$aporte_enero3</td><td>$retiros_enero3</td></tr><tr><td>Febrero</td><td>$aporte_febrero3</td><td>$retiros_febrero3</td></tr><tr><td>Marzo</td><td>$aporte_marzo3</td><td>$retiros_marzo3</td></tr><tr><td>Abril</td><td>$aporte_abril3</td><td>$retiros_abril3</td></tr><tr><td>Mayo</td><td>$aporte_mayo3</td><td>$retiros_mayo3</td></tr><tr><td>Junio</td><td>$aporte_junio3</td><td>$retiros_junio3</td></tr><tr><td>Julio</td><td>$aporte_julio3</td><td>$retiros_julio3</td></tr><tr><td>Agosto</td><td>$aporte_agosto3</td><td>$retiros_agosto3</td></tr><tr><td>Septiembre</td><td>$aporte_septiembre3</td><td>$retiros_septiembre3</td></tr><tr><td>Octubre</td><td>$aporte_octubre3</td><td>$retiros_octubre3</td></tr><tr><td>Noviembre</td><td>$aporte_noviembre3</td><td>$retiros_noviembre3</td></tr><tr><td>Diciembre</td><td>$aporte_diciembre3</td><td>$retiros_diciembre3</td></tr></table></center>";
$ahorro_2020=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2019'){
$query2=sprintf("SELECT * FROM ahorros_2019 WHERE cedula LIKE '$cedula'");
$query3=sprintf("SELECT * FROM retirable_2019 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$resultado3=mysqli_query($sgstec,$query3);
$row2 = mysqli_fetch_assoc($resultado2);
$row3 = mysqli_fetch_assoc($resultado3);
$aporte_enero=$row2['aporte_enero'];
$comentarios_enero=$row2['comentarios_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$comentarios_febrero=$row2['comentarios_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$comentarios_marzo=$row2['comentarios_marzo'];
$aporte_abril=$row2['aporte_abril'];
$comentarios_abril=$row2['comentarios_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$comentarios_mayo=$row2['comentarios_mayo'];
$aporte_junio=$row2['aporte_junio'];
$comentarios_junio=$row2['comentarios_junio'];
$aporte_julio=$row2['aporte_julio'];
$comentarios_julio=$row2['comentarios_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$comentarios_agosto=$row2['comentarios_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$comentarios_septiembre=$row2['comentarios_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$comentarios_octubre=$row2['comentarios_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$comentarios_noviembre=$row2['comentarios_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$comentarios_diciembre=$row2['comentarios_diciembre'];
$aporte_enero3=$row3['aporte_enero'];
$retiros_enero3=$row3['retiros_enero'];
$aporte_febrero3=$row3['aporte_febrero'];
$retiros_febrero3=$row3['retiros_febrero'];
$aporte_marzo3=$row3['aporte_marzo'];
$retiros_marzo3=$row3['retiros_marzo'];
$aporte_abril3=$row3['aporte_abril'];
$retiros_abril3=$row3['retiros_abril'];
$aporte_mayo3=$row3['aporte_mayo'];
$retiros_mayo3=$row3['retiros_mayo'];
$aporte_junio3=$row3['aporte_junio'];
$retiros_junio3=$row3['retiros_junio'];
$aporte_julio3=$row3['aporte_julio'];
$retiros_julio3=$row3['retiros_julio'];
$aporte_agosto3=$row3['aporte_agosto'];
$retiros_agosto3=$row3['retiros_agosto'];
$aporte_septiembre3=$row3['aporte_septiembre'];
$retiros_septiembre3=$row3['retiros_septiembre'];
$aporte_octubre3=$row3['aporte_octubre'];
$retiros_octubre3=$row3['retiros_octubre'];
$aporte_noviembre3=$row3['aporte_noviembre'];
$retiros_noviembre3=$row3['retiros_noviembre'];
$aporte_diciembre3=$row3['aporte_diciembre'];
$retiros_diciembre3=$row3['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2019</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Comentarios</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".$comentarios_enero."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".$comentarios_febrero."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".$comentarios_marzo."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".$comentarios_abril."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".$comentarios_mayo."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".$comentarios_junio."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".$comentarios_julio."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".$comentarios_agosto."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".$comentarios_septiembre."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".$comentarios_octubre."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".$comentarios_noviembre."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".$comentarios_diciembre."</td></tr></table></center>";
echo"<table class='table'><th style='border: none;'><b>Ahorros Retirables 2019</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>$aporte_enero3</td><td>$retiros_enero3</td></tr><tr><td>Febrero</td><td>$aporte_febrero3</td><td>$retiros_febrero3</td></tr><tr><td>Marzo</td><td>$aporte_marzo3</td><td>$retiros_marzo3</td></tr><tr><td>Abril</td><td>$aporte_abril3</td><td>$retiros_abril3</td></tr><tr><td>Mayo</td><td>$aporte_mayo3</td><td>$retiros_mayo3</td></tr><tr><td>Junio</td><td>$aporte_junio3</td><td>$retiros_junio3</td></tr><tr><td>Julio</td><td>$aporte_julio3</td><td>$retiros_julio3</td></tr><tr><td>Agosto</td><td>$aporte_agosto3</td><td>$retiros_agosto3</td></tr><tr><td>Septiembre</td><td>$aporte_septiembre3</td><td>$retiros_septiembre3</td></tr><tr><td>Octubre</td><td>$aporte_octubre3</td><td>$retiros_octubre3</td></tr><tr><td>Noviembre</td><td>$aporte_noviembre3</td><td>$retiros_noviembre3</td></tr><tr><td>Diciembre</td><td>$aporte_diciembre3</td><td>$retiros_diciembre3</td></tr></table></center>";
$ahorro_2019=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2018'){
$query2=sprintf("SELECT * FROM ahorros_2018 WHERE cedula LIKE '$cedula'");
$query3=sprintf("SELECT * FROM retirable_2018 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$resultado3=mysqli_query($sgstec,$query3);
$row2 = mysqli_fetch_assoc($resultado2);
$row3 = mysqli_fetch_assoc($resultado3);
$aporte_enero=$row2['aporte_enero'];
$comentarios_enero=$row2['comentarios_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$comentarios_febrero=$row2['comentarios_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$comentarios_marzo=$row2['comentarios_marzo'];
$aporte_abril=$row2['aporte_abril'];
$comentarios_abril=$row2['comentarios_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$comentarios_mayo=$row2['comentarios_mayo'];
$aporte_junio=$row2['aporte_junio'];
$comentarios_junio=$row2['comentarios_junio'];
$aporte_julio=$row2['aporte_julio'];
$comentarios_julio=$row2['comentarios_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$comentarios_agosto=$row2['comentarios_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$comentarios_septiembre=$row2['comentarios_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$comentarios_octubre=$row2['comentarios_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$comentarios_noviembre=$row2['comentarios_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$comentarios_diciembre=$row2['comentarios_diciembre'];
$aporte_enero3=$row3['aporte_enero'];
$retiros_enero3=$row3['retiros_enero'];
$aporte_febrero3=$row3['aporte_febrero'];
$retiros_febrero3=$row3['retiros_febrero'];
$aporte_marzo3=$row3['aporte_marzo'];
$retiros_marzo3=$row3['retiros_marzo'];
$aporte_abril3=$row3['aporte_abril'];
$retiros_abril3=$row3['retiros_abril'];
$aporte_mayo3=$row3['aporte_mayo'];
$retiros_mayo3=$row3['retiros_mayo'];
$aporte_junio3=$row3['aporte_junio'];
$retiros_junio3=$row3['retiros_junio'];
$aporte_julio3=$row3['aporte_julio'];
$retiros_julio3=$row3['retiros_julio'];
$aporte_agosto3=$row3['aporte_agosto'];
$retiros_agosto3=$row3['retiros_agosto'];
$aporte_septiembre3=$row3['aporte_septiembre'];
$retiros_septiembre3=$row3['retiros_septiembre'];
$aporte_octubre3=$row3['aporte_octubre'];
$retiros_octubre3=$row3['retiros_octubre'];
$aporte_noviembre3=$row3['aporte_noviembre'];
$retiros_noviembre3=$row3['retiros_noviembre'];
$aporte_diciembre3=$row3['aporte_diciembre'];
$retiros_diciembre3=$row3['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2018</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Comentarios</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".$comentarios_enero."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".$comentarios_febrero."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".$comentarios_marzo."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".$comentarios_abril."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".$comentarios_mayo."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".$comentarios_junio."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".$comentarios_julio."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".$comentarios_agosto."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".$comentarios_septiembre."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".$comentarios_octubre."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".$comentarios_noviembre."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".$comentarios_diciembre."</td></tr></table></center>";
echo"<table class='table'><th style='border: none;'><b>Ahorros Retirables 2018</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>$aporte_enero3</td><td>$retiros_enero3</td></tr><tr><td>Febrero</td><td>$aporte_febrero3</td><td>$retiros_febrero3</td></tr><tr><td>Marzo</td><td>$aporte_marzo3</td><td>$retiros_marzo3</td></tr><tr><td>Abril</td><td>$aporte_abril3</td><td>$retiros_abril3</td></tr><tr><td>Mayo</td><td>$aporte_mayo3</td><td>$retiros_mayo3</td></tr><tr><td>Junio</td><td>$aporte_junio3</td><td>$retiros_junio3</td></tr><tr><td>Julio</td><td>$aporte_julio3</td><td>$retiros_julio3</td></tr><tr><td>Agosto</td><td>$aporte_agosto3</td><td>$retiros_agosto3</td></tr><tr><td>Septiembre</td><td>$aporte_septiembre3</td><td>$retiros_septiembre3</td></tr><tr><td>Octubre</td><td>$aporte_octubre3</td><td>$retiros_octubre3</td></tr><tr><td>Noviembre</td><td>$aporte_noviembre3</td><td>$retiros_noviembre3</td></tr><tr><td>Diciembre</td><td>$aporte_diciembre3</td><td>$retiros_diciembre3</td></tr></table></center>";
$ahorro_2018=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2017'){
$query2=sprintf("SELECT * FROM ahorros_2017 WHERE cedula LIKE '$cedula'");
$query3=sprintf("SELECT * FROM retirable_2017 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$resultado3=mysqli_query($sgstec,$query3);
$row2 = mysqli_fetch_assoc($resultado2);
$row3 = mysqli_fetch_assoc($resultado3);
$aporte_enero=$row2['aporte_enero'];
$comentarios_enero=$row2['comentarios_enero'];
$retiros_enero=$row2['retiros_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$comentarios_febrero=$row2['comentarios_febrero'];
$retiros_febrero=$row2['retiros_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$comentarios_marzo=$row2['comentarios_marzo'];
$retiros_marzo=$row2['retiros_marzo'];
$aporte_abril=$row2['aporte_abril'];
$comentarios_abril=$row2['comentarios_abril'];
$retiros_abril=$row2['retiros_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$comentarios_mayo=$row2['comentarios_mayo'];
$retiros_mayo=$row2['retiros_mayo'];
$aporte_junio=$row2['aporte_junio'];
$comentarios_junio=$row2['comentarios_junio'];
$retiros_junio=$row2['retiros_junio'];
$aporte_julio=$row2['aporte_julio'];
$comentarios_julio=$row2['comentarios_julio'];
$retiros_julio=$row2['retiros_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$comentarios_agosto=$row2['comentarios_agosto'];
$retiros_agosto=$row2['retiros_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$comentarios_septiembre=$row2['comentarios_septiembre'];
$retiros_septiembre=$row2['retiros_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$comentarios_octubre=$row2['comentarios_octubre'];
$retiros_octubre=$row2['retiros_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$comentarios_noviembre=$row2['comentarios_noviembre'];
$retiros_noviembre=$row2['retiros_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$comentarios_diciembre=$row2['comentarios_diciembre'];
$retiros_diciembre=$row2['retiros_diciembre'];
$aporte_enero3=$row3['aporte_enero'];
$retiros_enero3=$row3['retiros_enero'];
$aporte_febrero3=$row3['aporte_febrero'];
$retiros_febrero3=$row3['retiros_febrero'];
$aporte_marzo3=$row3['aporte_marzo'];
$retiros_marzo3=$row3['retiros_marzo'];
$aporte_abril3=$row3['aporte_abril'];
$retiros_abril3=$row3['retiros_abril'];
$aporte_mayo3=$row3['aporte_mayo'];
$retiros_mayo3=$row3['retiros_mayo'];
$aporte_junio3=$row3['aporte_junio'];
$retiros_junio3=$row3['retiros_junio'];
$aporte_julio3=$row3['aporte_julio'];
$retiros_julio3=$row3['retiros_julio'];
$aporte_agosto3=$row3['aporte_agosto'];
$retiros_agosto3=$row3['retiros_agosto'];
$aporte_septiembre3=$row3['aporte_septiembre'];
$retiros_septiembre3=$row3['retiros_septiembre'];
$aporte_octubre3=$row3['aporte_octubre'];
$retiros_octubre3=$row3['retiros_octubre'];
$aporte_noviembre3=$row3['aporte_noviembre'];
$retiros_noviembre3=$row3['retiros_noviembre'];
$aporte_diciembre3=$row3['aporte_diciembre'];
$retiros_diciembre3=$row3['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2017</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Comentarios</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".$comentarios_enero."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".$comentarios_febrero."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".$comentarios_marzo."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".$comentarios_abril."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".$comentarios_mayo."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".$comentarios_junio."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".$comentarios_julio."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".$comentarios_agosto."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".$comentarios_septiembre."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".$comentarios_octubre."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".$comentarios_noviembre."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".$comentarios_diciembre."</td></tr></table></center>";
echo"<table class='table'><th style='border: none;'><b>Ahorros Retirables 2017</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>$aporte_enero3</td><td>$retiros_enero3</td></tr><tr><td>Febrero</td><td>$aporte_febrero3</td><td>$retiros_febrero3</td></tr><tr><td>Marzo</td><td>$aporte_marzo3</td><td>$retiros_marzo3</td></tr><tr><td>Abril</td><td>$aporte_abril3</td><td>$retiros_abril3</td></tr><tr><td>Mayo</td><td>$aporte_mayo3</td><td>$retiros_mayo3</td></tr><tr><td>Junio</td><td>$aporte_junio3</td><td>$retiros_junio3</td></tr><tr><td>Julio</td><td>$aporte_julio3</td><td>$retiros_julio3</td></tr><tr><td>Agosto</td><td>$aporte_agosto3</td><td>$retiros_agosto3</td></tr><tr><td>Septiembre</td><td>$aporte_septiembre3</td><td>$retiros_septiembre3</td></tr><tr><td>Octubre</td><td>$aporte_octubre3</td><td>$retiros_octubre3</td></tr><tr><td>Noviembre</td><td>$aporte_noviembre3</td><td>$retiros_noviembre3</td></tr><tr><td>Diciembre</td><td>$aporte_diciembre3</td><td>$retiros_diciembre3</td></tr></table></center>";
$ahorro_2017=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2016'){
$query2=sprintf("SELECT * FROM ahorros_2016 WHERE cedula LIKE '$cedula'");
$query3=sprintf("SELECT * FROM retirable_2016 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$resultado3=mysqli_query($sgstec,$query3);
$row2 = mysqli_fetch_assoc($resultado2);
$row3 = mysqli_fetch_assoc($resultado3);
$aporte_enero=$row2['aporte_enero'];
$comentarios_enero=$row2['comentarios_enero'];
$retiros_enero=$row2['retiros_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$comentarios_febrero=$row2['comentarios_febrero'];
$retiros_febrero=$row2['retiros_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$comentarios_marzo=$row2['comentarios_marzo'];
$retiros_marzo=$row2['retiros_marzo'];
$aporte_abril=$row2['aporte_abril'];
$comentarios_abril=$row2['comentarios_abril'];
$retiros_abril=$row2['retiros_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$comentarios_mayo=$row2['comentarios_mayo'];
$retiros_mayo=$row2['retiros_mayo'];
$aporte_junio=$row2['aporte_junio'];
$comentarios_junio=$row2['comentarios_junio'];
$retiros_junio=$row2['retiros_junio'];
$aporte_julio=$row2['aporte_julio'];
$comentarios_julio=$row2['comentarios_julio'];
$retiros_julio=$row2['retiros_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$comentarios_agosto=$row2['comentarios_agosto'];
$retiros_agosto=$row2['retiros_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$comentarios_septiembre=$row2['comentarios_septiembre'];
$retiros_septiembre=$row2['retiros_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$comentarios_octubre=$row2['comentarios_octubre'];
$retiros_octubre=$row2['retiros_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$comentarios_noviembre=$row2['comentarios_noviembre'];
$retiros_noviembre=$row2['retiros_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$comentarios_diciembre=$row2['comentarios_diciembre'];
$retiros_diciembre=$row2['retiros_diciembre'];
$aporte_enero3=$row3['aporte_enero'];
$retiros_enero3=$row3['retiros_enero'];
$aporte_febrero3=$row3['aporte_febrero'];
$retiros_febrero3=$row3['retiros_febrero'];
$aporte_marzo3=$row3['aporte_marzo'];
$retiros_marzo3=$row3['retiros_marzo'];
$aporte_abril3=$row3['aporte_abril'];
$retiros_abril3=$row3['retiros_abril'];
$aporte_mayo3=$row3['aporte_mayo'];
$retiros_mayo3=$row3['retiros_mayo'];
$aporte_junio3=$row3['aporte_junio'];
$retiros_junio3=$row3['retiros_junio'];
$aporte_julio3=$row3['aporte_julio'];
$retiros_julio3=$row3['retiros_julio'];
$aporte_agosto3=$row3['aporte_agosto'];
$retiros_agosto3=$row3['retiros_agosto'];
$aporte_septiembre3=$row3['aporte_septiembre'];
$retiros_septiembre3=$row3['retiros_septiembre'];
$aporte_octubre3=$row3['aporte_octubre'];
$retiros_octubre3=$row3['retiros_octubre'];
$aporte_noviembre3=$row3['aporte_noviembre'];
$retiros_noviembre3=$row3['retiros_noviembre'];
$aporte_diciembre3=$row3['aporte_diciembre'];
$retiros_diciembre3=$row3['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2016</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Comentarios</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".$comentarios_enero."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".$comentarios_febrero."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".$comentarios_marzo."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".$comentarios_abril."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".$comentarios_mayo."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".$comentarios_junio."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".$comentarios_julio."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".$comentarios_agosto."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".$comentarios_septiembre."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".$comentarios_octubre."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".$comentarios_noviembre."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".$comentarios_diciembre."</td></tr></table></center>";
echo"<table class='table'><th style='border: none;'><b>Ahorros Retirables 2016</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>$aporte_enero3</td><td>$retiros_enero3</td></tr><tr><td>Febrero</td><td>$aporte_febrero3</td><td>$retiros_febrero3</td></tr><tr><td>Marzo</td><td>$aporte_marzo3</td><td>$retiros_marzo3</td></tr><tr><td>Abril</td><td>$aporte_abril3</td><td>$retiros_abril3</td></tr><tr><td>Mayo</td><td>$aporte_mayo3</td><td>$retiros_mayo3</td></tr><tr><td>Junio</td><td>$aporte_junio3</td><td>$retiros_junio3</td></tr><tr><td>Julio</td><td>$aporte_julio3</td><td>$retiros_julio3</td></tr><tr><td>Agosto</td><td>$aporte_agosto3</td><td>$retiros_agosto3</td></tr><tr><td>Septiembre</td><td>$aporte_septiembre3</td><td>$retiros_septiembre3</td></tr><tr><td>Octubre</td><td>$aporte_octubre3</td><td>$retiros_octubre3</td></tr><tr><td>Noviembre</td><td>$aporte_noviembre3</td><td>$retiros_noviembre3</td></tr><tr><td>Diciembre</td><td>$aporte_diciembre3</td><td>$retiros_diciembre3</td></tr></table></center>";
$ahorro_2016=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2015'){
$query2=sprintf("SELECT * FROM ahorros_2015 WHERE cedula LIKE '$cedula'");
$query3=sprintf("SELECT * FROM retirable_2015 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$resultado3=mysqli_query($sgstec,$query3);
$row2 = mysqli_fetch_assoc($resultado2);
$row3 = mysqli_fetch_assoc($resultado3);
$aporte_enero=$row2['aporte_enero'];
$comentarios_enero=$row2['comentarios_enero'];
$retiros_enero=$row2['retiros_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$comentarios_febrero=$row2['comentarios_febrero'];
$retiros_febrero=$row2['retiros_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$comentarios_marzo=$row2['comentarios_marzo'];
$retiros_marzo=$row2['retiros_marzo'];
$aporte_abril=$row2['aporte_abril'];
$comentarios_abril=$row2['comentarios_abril'];
$retiros_abril=$row2['retiros_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$comentarios_mayo=$row2['comentarios_mayo'];
$retiros_mayo=$row2['retiros_mayo'];
$aporte_junio=$row2['aporte_junio'];
$comentarios_junio=$row2['comentarios_junio'];
$retiros_junio=$row2['retiros_junio'];
$aporte_julio=$row2['aporte_julio'];
$comentarios_julio=$row2['comentarios_julio'];
$retiros_julio=$row2['retiros_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$comentarios_agosto=$row2['comentarios_agosto'];
$retiros_agosto=$row2['retiros_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$comentarios_septiembre=$row2['comentarios_septiembre'];
$retiros_septiembre=$row2['retiros_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$comentarios_octubre=$row2['comentarios_octubre'];
$retiros_octubre=$row2['retiros_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$comentarios_noviembre=$row2['comentarios_noviembre'];
$retiros_noviembre=$row2['retiros_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$comentarios_diciembre=$row2['comentarios_diciembre'];
$retiros_diciembre=$row2['retiros_diciembre'];
$aporte_enero3=$row3['aporte_enero'];
$retiros_enero3=$row3['retiros_enero'];
$aporte_febrero3=$row3['aporte_febrero'];
$retiros_febrero3=$row3['retiros_febrero'];
$aporte_marzo3=$row3['aporte_marzo'];
$retiros_marzo3=$row3['retiros_marzo'];
$aporte_abril3=$row3['aporte_abril'];
$retiros_abril3=$row3['retiros_abril'];
$aporte_mayo3=$row3['aporte_mayo'];
$retiros_mayo3=$row3['retiros_mayo'];
$aporte_junio3=$row3['aporte_junio'];
$retiros_junio3=$row3['retiros_junio'];
$aporte_julio3=$row3['aporte_julio'];
$retiros_julio3=$row3['retiros_julio'];
$aporte_agosto3=$row3['aporte_agosto'];
$retiros_agosto3=$row3['retiros_agosto'];
$aporte_septiembre3=$row3['aporte_septiembre'];
$retiros_septiembre3=$row3['retiros_septiembre'];
$aporte_octubre3=$row3['aporte_octubre'];
$retiros_octubre3=$row3['retiros_octubre'];
$aporte_noviembre3=$row3['aporte_noviembre'];
$retiros_noviembre3=$row3['retiros_noviembre'];
$aporte_diciembre3=$row3['aporte_diciembre'];
$retiros_diciembre3=$row3['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2015</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Comentarios</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".$comentarios_enero."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".$comentarios_febrero."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".$comentarios_marzo."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".$comentarios_abril."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".$comentarios_mayo."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".$comentarios_junio."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".$comentarios_julio."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".$comentarios_agosto."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".$comentarios_septiembre."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".$comentarios_octubre."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".$comentarios_noviembre."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".$comentarios_diciembre."</td></tr></table></center>";
echo"<table class='table'><th style='border: none;'><b>Ahorros Retirables 2015</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>$aporte_enero3</td><td>$retiros_enero3</td></tr><tr><td>Febrero</td><td>$aporte_febrero3</td><td>$retiros_febrero3</td></tr><tr><td>Marzo</td><td>$aporte_marzo3</td><td>$retiros_marzo3</td></tr><tr><td>Abril</td><td>$aporte_abril3</td><td>$retiros_abril3</td></tr><tr><td>Mayo</td><td>$aporte_mayo3</td><td>$retiros_mayo3</td></tr><tr><td>Junio</td><td>$aporte_junio3</td><td>$retiros_junio3</td></tr><tr><td>Julio</td><td>$aporte_julio3</td><td>$retiros_julio3</td></tr><tr><td>Agosto</td><td>$aporte_agosto3</td><td>$retiros_agosto3</td></tr><tr><td>Septiembre</td><td>$aporte_septiembre3</td><td>$retiros_septiembre3</td></tr><tr><td>Octubre</td><td>$aporte_octubre3</td><td>$retiros_octubre3</td></tr><tr><td>Noviembre</td><td>$aporte_noviembre3</td><td>$retiros_noviembre3</td></tr><tr><td>Diciembre</td><td>$aporte_diciembre3</td><td>$retiros_diciembre3</td></tr></table></center>";
$ahorro_2015=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2014'){
$query2=sprintf("SELECT * FROM ahorros_2014 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$row2 = mysqli_fetch_assoc($resultado2);
$aporte_enero=$row2['aporte_enero'];
$retiros_enero=$row2['retiros_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$retiros_febrero=$row2['retiros_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$retiros_marzo=$row2['retiros_marzo'];
$aporte_abril=$row2['aporte_abril'];
$retiros_abril=$row2['retiros_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$retiros_mayo=$row2['retiros_mayo'];
$aporte_junio=$row2['aporte_junio'];
$retiros_junio=$row2['retiros_junio'];
$aporte_julio=$row2['aporte_julio'];
$retiros_julio=$row2['retiros_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$retiros_agosto=$row2['retiros_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$retiros_septiembre=$row2['retiros_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$retiros_octubre=$row2['retiros_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$retiros_noviembre=$row2['retiros_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$retiros_diciembre=$row2['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2014</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";
$ahorro_2014=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2013'){
$query2=sprintf("SELECT * FROM ahorros_2013 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$row2 = mysqli_fetch_assoc($resultado2);
$aporte_enero=$row2['aporte_enero'];
$retiros_enero=$row2['retiros_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$retiros_febrero=$row2['retiros_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$retiros_marzo=$row2['retiros_marzo'];
$aporte_abril=$row2['aporte_abril'];
$retiros_abril=$row2['retiros_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$retiros_mayo=$row2['retiros_mayo'];
$aporte_junio=$row2['aporte_junio'];
$retiros_junio=$row2['retiros_junio'];
$aporte_julio=$row2['aporte_julio'];
$retiros_julio=$row2['retiros_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$retiros_agosto=$row2['retiros_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$retiros_septiembre=$row2['retiros_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$retiros_octubre=$row2['retiros_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$retiros_noviembre=$row2['retiros_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$retiros_diciembre=$row2['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2013</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";
$ahorro_2013=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2012'){
$query2=sprintf("SELECT * FROM ahorros_2012 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$row2 = mysqli_fetch_assoc($resultado2);
$aporte_enero=$row2['aporte_enero'];
$retiros_enero=$row2['retiros_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$retiros_febrero=$row2['retiros_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$retiros_marzo=$row2['retiros_marzo'];
$aporte_abril=$row2['aporte_abril'];
$retiros_abril=$row2['retiros_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$retiros_mayo=$row2['retiros_mayo'];
$aporte_junio=$row2['aporte_junio'];
$retiros_junio=$row2['retiros_junio'];
$aporte_julio=$row2['aporte_julio'];
$retiros_julio=$row2['retiros_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$retiros_agosto=$row2['retiros_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$retiros_septiembre=$row2['retiros_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$retiros_octubre=$row2['retiros_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$retiros_noviembre=$row2['retiros_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$retiros_diciembre=$row2['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2012</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".number_format($retiros_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".number_format($retiros_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".number_format($retiros_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".number_format($retiros_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".number_format($retiros_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".number_format($retiros_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".number_format($retiros_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".number_format($retiros_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".number_format($retiros_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".number_format($retiros_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".number_format($retiros_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".number_format($retiros_diciembre,2,".",",")."</td></tr></table></center>";
$ahorro_2012=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === '2011'){
$query2=sprintf("SELECT * FROM ahorros_2011 WHERE cedula LIKE '$cedula'");
$resultado2=mysqli_query($sgstec,$query2);
$row2 = mysqli_fetch_assoc($resultado2);
$aporte_enero=$row2['aporte_enero'];
$retiros_enero=$row2['retiros_enero'];
$aporte_febrero=$row2['aporte_febrero'];
$retiros_febrero=$row2['retiros_febrero'];
$aporte_marzo=$row2['aporte_marzo'];
$retiros_marzo=$row2['retiros_marzo'];
$aporte_abril=$row2['aporte_abril'];
$retiros_abril=$row2['retiros_abril'];
$aporte_mayo=$row2['aporte_mayo'];
$retiros_mayo=$row2['retiros_mayo'];
$aporte_junio=$row2['aporte_junio'];
$retiros_junio=$row2['retiros_junio'];
$aporte_julio=$row2['aporte_julio'];
$retiros_julio=$row2['retiros_julio'];
$aporte_agosto=$row2['aporte_agosto'];
$retiros_agosto=$row2['retiros_agosto'];
$aporte_septiembre=$row2['aporte_septiembre'];
$retiros_septiembre=$row2['retiros_septiembre'];
$aporte_octubre=$row2['aporte_octubre'];
$retiros_octubre=$row2['retiros_octubre'];
$aporte_noviembre=$row2['aporte_noviembre'];
$retiros_noviembre=$row2['retiros_noviembre'];
$aporte_diciembre=$row2['aporte_diciembre'];
$retiros_diciembre=$row2['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2011</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".number_format($retiros_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".number_format($retiros_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".number_format($retiros_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".number_format($retiros_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".number_format($retiros_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".number_format($retiros_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".number_format($retiros_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".number_format($retiros_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".number_format($retiros_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".number_format($retiros_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".number_format($retiros_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".number_format($retiros_diciembre,2,".",",")."</td></tr></table></center>";
$ahorro_2011=$aporte_enero+$aporte_febrero+$aporte_marzo+$aporte_abril+$aporte_mayo+$aporte_junio+$aporte_julio+$aporte_agosto+$aporte_septiembre+$aporte_octubre+$aporte_noviembre+$aporte_diciembre;
}
?>
<?php
if ($sitio === 'Todos'){
	
			$query2021=sprintf("SELECT * FROM ahorros_2021 WHERE cedula LIKE '$cedula'");
$resultado2021=mysqli_query($sgstec,$query2021);
$row2021 = mysqli_fetch_assoc($resultado2021);
$aporte_enero=$row2021['aporte_enero'];
$aporte_febrero=$row2021['aporte_febrero'];
$aporte_marzo=$row2021['aporte_marzo'];
$aporte_abril=$row2021['aporte_abril'];
$aporte_mayo=$row2021['aporte_mayo'];
$aporte_junio=$row2021['aporte_junio'];
$aporte_julio=$row2021['aporte_julio'];
$aporte_agosto=$row2021['aporte_agosto'];
$aporte_septiembre=$row2021['aporte_septiembre'];
$aporte_octubre=$row2021['aporte_octubre'];
$aporte_noviembre=$row2021['aporte_noviembre'];
$aporte_diciembre=$row2021['aporte_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2021</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";

	
		$query2020=sprintf("SELECT * FROM ahorros_2020 WHERE cedula LIKE '$cedula'");
$resultado2020=mysqli_query($sgstec,$query2020);
$row2020 = mysqli_fetch_assoc($resultado2020);
$aporte_enero=$row2020['aporte_enero'];
$aporte_febrero=$row2020['aporte_febrero'];
$aporte_marzo=$row2020['aporte_marzo'];
$aporte_abril=$row2020['aporte_abril'];
$aporte_mayo=$row2020['aporte_mayo'];
$aporte_junio=$row2020['aporte_junio'];
$aporte_julio=$row2020['aporte_julio'];
$aporte_agosto=$row2020['aporte_agosto'];
$aporte_septiembre=$row2020['aporte_septiembre'];
$aporte_octubre=$row2020['aporte_octubre'];
$aporte_noviembre=$row2020['aporte_noviembre'];
$aporte_diciembre=$row2020['aporte_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2020</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";
	
	
		$query2019=sprintf("SELECT * FROM ahorros_2019 WHERE cedula LIKE '$cedula'");
$resultado2019=mysqli_query($sgstec,$query2019);
$row2019 = mysqli_fetch_assoc($resultado2019);
$aporte_enero=$row2019['aporte_enero'];
$aporte_febrero=$row2019['aporte_febrero'];
$aporte_marzo=$row2019['aporte_marzo'];
$aporte_abril=$row2019['aporte_abril'];
$aporte_mayo=$row2019['aporte_mayo'];
$aporte_junio=$row2019['aporte_junio'];
$aporte_julio=$row2019['aporte_julio'];
$aporte_agosto=$row2019['aporte_agosto'];
$aporte_septiembre=$row2019['aporte_septiembre'];
$aporte_octubre=$row2019['aporte_octubre'];
$aporte_noviembre=$row2019['aporte_noviembre'];
$aporte_diciembre=$row2019['aporte_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2019</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";

	
		$query2018=sprintf("SELECT * FROM ahorros_2018 WHERE cedula LIKE '$cedula'");
$resultado2018=mysqli_query($sgstec,$query2018);
$row2018 = mysqli_fetch_assoc($resultado2018);
$aporte_enero=$row2018['aporte_enero'];
$aporte_febrero=$row2018['aporte_febrero'];
$aporte_marzo=$row2018['aporte_marzo'];
$aporte_abril=$row2018['aporte_abril'];
$aporte_mayo=$row2018['aporte_mayo'];
$aporte_junio=$row2018['aporte_junio'];
$aporte_julio=$row2018['aporte_julio'];
$aporte_agosto=$row2018['aporte_agosto'];
$aporte_septiembre=$row2018['aporte_septiembre'];
$aporte_octubre=$row2018['aporte_octubre'];
$aporte_noviembre=$row2018['aporte_noviembre'];
$aporte_diciembre=$row2018['aporte_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2018</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";

	$query2017=sprintf("SELECT * FROM ahorros_2017 WHERE cedula LIKE '$cedula'");
$resultado2017=mysqli_query($sgstec,$query2017);
$row2017 = mysqli_fetch_assoc($resultado2017);
$aporte_enero=$row2017['aporte_enero'];
$aporte_febrero=$row2017['aporte_febrero'];
$aporte_marzo=$row2017['aporte_marzo'];
$aporte_abril=$row2017['aporte_abril'];
$aporte_mayo=$row2017['aporte_mayo'];
$aporte_junio=$row2017['aporte_junio'];
$aporte_julio=$row2017['aporte_julio'];
$aporte_agosto=$row2017['aporte_agosto'];
$aporte_septiembre=$row2017['aporte_septiembre'];
$aporte_octubre=$row2017['aporte_octubre'];
$aporte_noviembre=$row2017['aporte_noviembre'];
$aporte_diciembre=$row2017['aporte_diciembre'];

echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2017</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";
$query2016=sprintf("SELECT * FROM ahorros_2016 WHERE cedula LIKE '$cedula'");
$resultado2016=mysqli_query($sgstec,$query2016);
$row2016 = mysqli_fetch_assoc($resultado2016);
$aporte_enero=$row2016['aporte_enero'];
$retiros_enero=$row2016['retiros_enero'];
$aporte_febrero=$row2016['aporte_febrero'];
$retiros_febrero=$row2016['retiros_febrero'];
$aporte_marzo=$row2016['aporte_marzo'];
$retiros_marzo=$row2016['retiros_marzo'];
$aporte_abril=$row2016['aporte_abril'];
$retiros_abril=$row2016['retiros_abril'];
$aporte_mayo=$row2016['aporte_mayo'];
$retiros_mayo=$row2016['retiros_mayo'];
$aporte_junio=$row2016['aporte_junio'];
$retiros_junio=$row2016['retiros_junio'];
$aporte_julio=$row2016['aporte_julio'];
$retiros_julio=$row2016['retiros_julio'];
$aporte_agosto=$row2016['aporte_agosto'];
$retiros_agosto=$row2016['retiros_agosto'];
$aporte_septiembre=$row2016['aporte_septiembre'];
$retiros_septiembre=$row2016['retiros_septiembre'];
$aporte_octubre=$row2016['aporte_octubre'];
$retiros_octubre=$row2016['retiros_octubre'];
$aporte_noviembre=$row2016['aporte_noviembre'];
$retiros_noviembre=$row2016['retiros_noviembre'];
$aporte_diciembre=$row2016['aporte_diciembre'];
$retiros_diciembre=$row2016['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2016</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";
$query2015=sprintf("SELECT * FROM ahorros_2015 WHERE cedula LIKE '$cedula'");
$resultado2015=mysqli_query($sgstec,$query2015);
$row2015 = mysqli_fetch_assoc($resultado2015);
$aporte_enero=$row2015['aporte_enero'];
$retiros_enero=$row2015['retiros_enero'];
$aporte_febrero=$row2015['aporte_febrero'];
$retiros_febrero=$row2015['retiros_febrero'];
$aporte_marzo=$row2015['aporte_marzo'];
$retiros_marzo=$row2015['retiros_marzo'];
$aporte_abril=$row2015['aporte_abril'];
$retiros_abril=$row2015['retiros_abril'];
$aporte_mayo=$row2015['aporte_mayo'];
$retiros_mayo=$row2015['retiros_mayo'];
$aporte_junio=$row2015['aporte_junio'];
$retiros_junio=$row2015['retiros_junio'];
$aporte_julio=$row2015['aporte_julio'];
$retiros_julio=$row2015['retiros_julio'];
$aporte_agosto=$row2015['aporte_agosto'];
$retiros_agosto=$row2015['retiros_agosto'];
$aporte_septiembre=$row2015['aporte_septiembre'];
$retiros_septiembre=$row2015['retiros_septiembre'];
$aporte_octubre=$row2015['aporte_octubre'];
$retiros_octubre=$row2015['retiros_octubre'];
$aporte_noviembre=$row2015['aporte_noviembre'];
$retiros_noviembre=$row2015['retiros_noviembre'];
$aporte_diciembre=$row2015['aporte_diciembre'];
$retiros_diciembre=$row2015['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2015</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";

$query2014=sprintf("SELECT * FROM ahorros_2014 WHERE cedula LIKE '$cedula'");
$resultado2014=mysqli_query($sgstec,$query2014);
$row2014 = mysqli_fetch_assoc($resultado2014);
$aporte_enero=$row2014['aporte_enero'];
$retiros_enero=$row2014['retiros_enero'];
$aporte_febrero=$row2014['aporte_febrero'];
$retiros_febrero=$row2014['retiros_febrero'];
$aporte_marzo=$row2014['aporte_marzo'];
$retiros_marzo=$row2014['retiros_marzo'];
$aporte_abril=$row2014['aporte_abril'];
$retiros_abril=$row2014['retiros_abril'];
$aporte_mayo=$row2014['aporte_mayo'];
$retiros_mayo=$row2014['retiros_mayo'];
$aporte_junio=$row2014['aporte_junio'];
$retiros_junio=$row2014['retiros_junio'];
$aporte_julio=$row2014['aporte_julio'];
$retiros_julio=$row2014['retiros_julio'];
$aporte_agosto=$row2014['aporte_agosto'];
$retiros_agosto=$row2014['retiros_agosto'];
$aporte_septiembre=$row2014['aporte_septiembre'];
$retiros_septiembre=$row2014['retiros_septiembre'];
$aporte_octubre=$row2014['aporte_octubre'];
$retiros_octubre=$row2014['retiros_octubre'];
$aporte_noviembre=$row2014['aporte_noviembre'];
$retiros_noviembre=$row2014['retiros_noviembre'];
$aporte_diciembre=$row2014['aporte_diciembre'];
$retiros_diciembre=$row2014['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2014</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";
$query2013=sprintf("SELECT * FROM ahorros_2013 WHERE cedula LIKE '$cedula'");
$resultado2013=mysqli_query($sgstec,$query2013);
$row2013 = mysqli_fetch_assoc($resultado2013);
$aporte_enero=$row2013['aporte_enero'];
$retiros_enero=$row2013['retiros_enero'];
$aporte_febrero=$row2013['aporte_febrero'];
$retiros_febrero=$row2013['retiros_febrero'];
$aporte_marzo=$row2013['aporte_marzo'];
$retiros_marzo=$row2013['retiros_marzo'];
$aporte_abril=$row2013['aporte_abril'];
$retiros_abril=$row2013['retiros_abril'];
$aporte_mayo=$row2013['aporte_mayo'];
$retiros_mayo=$row2013['retiros_mayo'];
$aporte_junio=$row2013['aporte_junio'];
$retiros_junio=$row2013['retiros_junio'];
$aporte_julio=$row2013['aporte_julio'];
$retiros_julio=$row2013['retiros_julio'];
$aporte_agosto=$row2013['aporte_agosto'];
$retiros_agosto=$row2013['retiros_agosto'];
$aporte_septiembre=$row2013['aporte_septiembre'];
$retiros_septiembre=$row2013['retiros_septiembre'];
$aporte_octubre=$row2013['aporte_octubre'];
$retiros_octubre=$row2013['retiros_octubre'];
$aporte_noviembre=$row2013['aporte_noviembre'];
$retiros_noviembre=$row2013['retiros_noviembre'];
$aporte_diciembre=$row2013['aporte_diciembre'];
$retiros_diciembre=$row2013['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2013</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td></tr></table></center>";

$query2012=sprintf("SELECT * FROM ahorros_2012 WHERE cedula LIKE '$cedula'");
$resultado2012=mysqli_query($sgstec,$query2012);
$row2012 = mysqli_fetch_assoc($resultado2012);
$aporte_enero=$row2012['aporte_enero'];
$retiros_enero=$row2012['retiros_enero'];
$aporte_febrero=$row2012['aporte_febrero'];
$retiros_febrero=$row2012['retiros_febrero'];
$aporte_marzo=$row2012['aporte_marzo'];
$retiros_marzo=$row2012['retiros_marzo'];
$aporte_abril=$row2012['aporte_abril'];
$retiros_abril=$row2012['retiros_abril'];
$aporte_mayo=$row2012['aporte_mayo'];
$retiros_mayo=$row2012['retiros_mayo'];
$aporte_junio=$row2012['aporte_junio'];
$retiros_junio=$row2012['retiros_junio'];
$aporte_julio=$row2012['aporte_julio'];
$retiros_julio=$row2012['retiros_julio'];
$aporte_agosto=$row2012['aporte_agosto'];
$retiros_agosto=$row2012['retiros_agosto'];
$aporte_septiembre=$row2012['aporte_septiembre'];
$retiros_septiembre=$row2012['retiros_septiembre'];
$aporte_octubre=$row2012['aporte_octubre'];
$retiros_octubre=$row2012['retiros_octubre'];
$aporte_noviembre=$row2012['aporte_noviembre'];
$retiros_noviembre=$row2012['retiros_noviembre'];
$aporte_diciembre=$row2012['aporte_diciembre'];
$retiros_diciembre=$row2012['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2012</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".number_format($retiros_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".number_format($retiros_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".number_format($retiros_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".number_format($retiros_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".number_format($retiros_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".number_format($retiros_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".number_format($retiros_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".number_format($retiros_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".number_format($retiros_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".number_format($retiros_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".number_format($retiros_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".number_format($retiros_diciembre,2,".",",")."</td></tr></table></center>";

$query2011=sprintf("SELECT * FROM ahorros_2011 WHERE cedula LIKE '$cedula'");
$resultado2011=mysqli_query($sgstec,$query2011);
$row2011 = mysqli_fetch_assoc($resultado2011);
$aporte_enero=$row2011['aporte_enero'];
$retiros_enero=$row2011['retiros_enero'];
$aporte_febrero=$row2011['aporte_febrero'];
$retiros_febrero=$row2011['retiros_febrero'];
$aporte_marzo=$row2011['aporte_marzo'];
$retiros_marzo=$row2011['retiros_marzo'];
$aporte_abril=$row2011['aporte_abril'];
$retiros_abril=$row2011['retiros_abril'];
$aporte_mayo=$row2011['aporte_mayo'];
$retiros_mayo=$row2011['retiros_mayo'];
$aporte_junio=$row2011['aporte_junio'];
$retiros_junio=$row2011['retiros_junio'];
$aporte_julio=$row2011['aporte_julio'];
$retiros_julio=$row2011['retiros_julio'];
$aporte_agosto=$row2011['aporte_agosto'];
$retiros_agosto=$row2011['retiros_agosto'];
$aporte_septiembre=$row2011['aporte_septiembre'];
$retiros_septiembre=$row2011['retiros_septiembre'];
$aporte_octubre=$row2011['aporte_octubre'];
$retiros_octubre=$row2011['retiros_octubre'];
$aporte_noviembre=$row2011['aporte_noviembre'];
$retiros_noviembre=$row2011['retiros_noviembre'];
$aporte_diciembre=$row2011['aporte_diciembre'];
$retiros_diciembre=$row2011['retiros_diciembre'];
echo"<center><table class='table'><th style='border: none;'><b>Ahorros Normales 2011</b></th><tr><td><b>Mes</b></td><td><b>Ahorros</b></td><td><b>Retiros</b></td></tr><tr><td>Enero</td><td>".number_format($aporte_enero,2,".",",")."</td><td>".number_format($retiros_enero,2,".",",")."</td></tr><tr><td>Febrero</td><td>".number_format($aporte_febrero,2,".",",")."</td><td>".number_format($retiros_febrero,2,".",",")."</td></tr><tr><td>Marzo</td><td>".number_format($aporte_marzo,2,".",",")."</td><td>".number_format($retiros_marzo,2,".",",")."</td></tr><tr><td>Abril</td><td>".number_format($aporte_abril,2,".",",")."</td><td>".number_format($retiros_abril,2,".",",")."</td></tr><tr><td>Mayo</td><td>".number_format($aporte_mayo,2,".",",")."</td><td>".number_format($retiros_mayo,2,".",",")."</td></tr><tr><td>Junio</td><td>".number_format($aporte_junio,2,".",",")."</td><td>".number_format($retiros_junio,2,".",",")."</td></tr><tr><td>Julio</td><td>".number_format($aporte_julio,2,".",",")."</td><td>".number_format($retiros_julio,2,".",",")."</td></tr><tr><td>Agosto</td><td>".number_format($aporte_agosto,2,".",",")."</td><td>".number_format($retiros_agosto,2,".",",")."</td></tr><tr><td>Septiembre</td><td>".number_format($aporte_septiembre,2,".",",")."</td><td>".number_format($retiros_septiembre,2,".",",")."</td></tr><tr><td>Octubre</td><td>".number_format($aporte_octubre,2,".",",")."</td><td>".number_format($retiros_octubre,2,".",",")."</td></tr><tr><td>Noviembre</td><td>".number_format($aporte_noviembre,2,".",",")."</td><td>".number_format($retiros_noviembre,2,".",",")."</td></tr><tr><td>Diciembre</td><td>".number_format($aporte_diciembre,2,".",",")."</td><td>".number_format($retiros_diciembre,2,".",",")."</td></tr></table></center>";
}
?>