# Generated by Django 5.0.7 on 2024-07-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('id_ahorro', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('monto_ahorro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ahorro', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo_meses', models.IntegerField()),
                ('capital_pendiente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_primera_cuota', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('estatus_prestamo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id_retiro', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('monto_retiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_retiro', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id_tipo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_prestamo', models.CharField(max_length=50)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mora', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_ahorro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_ingreso_trabajo', models.DateField(blank=True, null=True)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('referido_por', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.prestamo')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipopago')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_tipo_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipoprestamo'),
        ),
    ]
