# Generated by Django 5.0.7 on 2024-07-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_ahorro_prestamo_retiro_tipopago_tipoprestamo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='description',
            new_name='descripcion',
        ),
    ]
