# Generated by Django 5.0.7 on 2024-07-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_description_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='fecha_ahorro',
            field=models.DateField(verbose_name='Fecha de Ahorro'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='id_ahorro',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ahorro'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='monto_ahorro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Ahorro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pagos',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.prestamo', verbose_name='Préstamo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipopago', verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_capital',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Capital'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_interes',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Interés'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='capital_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capital Pendiente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estatus_prestamo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estatus del Préstamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_primera_cuota',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Primera Cuota'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_solicitud',
            field=models.DateField(verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_prestamo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Préstamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_tipo_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipoprestamo', verbose_name='Tipo de Préstamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='plazo_meses',
            field=models.IntegerField(verbose_name='Plazo en Meses'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_retiro',
            field=models.DateField(verbose_name='Fecha de Retiro'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='id_retiro',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Retiro'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='monto_retiro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Retiro'),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='id_tipo_pago',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='tipo_pago',
            field=models.CharField(max_length=50, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='tipoprestamo',
            name='id_tipo_prestamo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tipo de Préstamo'),
        ),
        migrations.AlterField(
            model_name='tipoprestamo',
            name='interes',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interés'),
        ),
        migrations.AlterField(
            model_name='tipoprestamo',
            name='mora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mora'),
        ),
        migrations.AlterField(
            model_name='tipoprestamo',
            name='tipo_prestamo',
            field=models.CharField(max_length=50, verbose_name='Tipo de Préstamo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estatus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso a la Cooperativa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso_trabajo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso al Trabajo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida de la Cooperativa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Trabajo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='monto_ahorro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de Ahorro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='referido_por',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referido por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Trabajo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión'),
        ),
    ]
