# Generated by Django 5.0.7 on 2024-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_ahorro_cedula_alter_ahorro_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultima_conexion',
            field=models.DateField(blank=True, null=True, verbose_name='Última Conexión'),
        ),
    ]
