from django.urls import path
from .import views
from .views import (UsuarioDeleteView, AhorroDeleteView, RetiroDeleteView, TipoPrestamoDeleteView, 
                    PrestamoDeleteView, TipoPagoDeleteView, PagoDeleteView)


urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('libros', views.libros, name='libros'),
    path('usuarios', views.usuarios, name='usuarios'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('crear', views.crear, name='crear'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'),
    path('form', views.form, name='form'),
    path('form_usuario', views.form_usuario, name='form_usuario'),
    path('crear_usuario', views.crear_usuario, name='crear_usuario'),
    path('editar_usuario', views.editar_usuario, name='editar_usuario'),
    path('formulario_usuarios', views.formulario_usuarios, name='formulario_usuarios'),
    path('crear_ahorro', views.crear_ahorro, name='crear_ahorro'),
    path('editar_ahorro', views.editar_ahorro, name='editar_ahorro'),
    path('formulario_ahorro', views.formulario_ahorro, name='formulario_ahorro'),
    path('crear_retiro', views.crear_retiro, name='crear_retiro'),
    path('editar_retiro', views.editar_retiro, name='editar_retiro'),
    path('formulario_retiro', views.formulario_retiro, name='formulario_retiro'),
    path('crear_prestamo', views.crear_prestamo, name='crear_prestamo'),
    path('editar_prestamo', views.editar_prestamo, name='editar_prestamo'),
    path('formulario_prestamo', views.formulario_prestamo, name='formulario_prestamo'),
    path('crear_pago', views.crear_pago, name='crear_pago'),
    path('editar_pago', views.editar_pago, name='editar_pago'),
    path('formulario_pago', views.formulario_pago, name='formulario_pago'),
    path('crear_tipopago', views.crear_tipopago, name='crear_tipopago'),
    path('editar_tipopago', views.editar_tipopago, name='editar_tipopago'),
    path('formulario_tipopago', views.formulario_tipopago, name='formulario_tipopago'),
    path('crear_tipoprestamo', views.crear_tipoprestamo, name='crear_tipoprestamo'),
    path('editar_tipoprestamo', views.editar_tipoprestamo, name='editar_tipoprestamo'),
    path('formulario_tipoprestamo', views.formulario_tipoprestamo, name='formulario_tipoprestamo'),
    path('usuario/<int:pk>/eliminar/', UsuarioDeleteView.as_view(), name='usuario_eliminar'),
    path('ahorro/<int:pk>/eliminar/', AhorroDeleteView.as_view(), name='ahorro_eliminar'),
    path('retiro/<int:pk>/eliminar/', RetiroDeleteView.as_view(), name='retiro_eliminar'),
    path('tipoprestamo/<int:pk>/eliminar/', TipoPrestamoDeleteView.as_view(), name='tipoprestamo_eliminar'),
    path('prestamo/<int:pk>/eliminar/', PrestamoDeleteView.as_view(), name='prestamo_eliminar'),
    path('tipopago/<int:pk>/eliminar/', TipoPagoDeleteView.as_view(), name='tipopago_eliminar'),
    path('pago/<int:pk>/eliminar/', PagoDeleteView.as_view(), name='pago_eliminar'),
    ]
